# Generated by Django 4.2.3 on 2023-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('miles', models.DecimalField(decimal_places=1, max_digits=3)),
                ('destination', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
